parameters:
    redlabteam_helpers_debug: true
    redlabteam_helpers_notice_failure: true

services:
    logger:
        class: Symfony\Component\HttpKernel\Log\Logger
        arguments:
            $minLevel: null
            $output: '%kernel.logs_dir%/%kernel.environment%.log'
            $formatter: null

    redlabteam_helpers.arr:
        class: RedlabTeam\Helper\Arr
    RedlabTeam\Helper\Arr: '@redlabteam_helpers.arr'

    redlabteam_helpers.date:
        class: RedlabTeam\Helper\Date
    RedlabTeam\Helper\Date: '@redlabteam_helpers.date'

    redlabteam_helpers.json:
        class: RedlabTeam\HelpersBundle\Service\JsonService
        arguments:
            $logger: '@logger'
            $debug: '%redlabteam_helpers_debug%'
            $noticeFailure: '%redlabteam_helpers_notice_failure%'
    RedlabTeam\HelpersBundle\Service\JsonService: '@redlabteam_helpers.json'