parameters:
    redlabteam_helpers_debug: true
    redlabteam_helpers_notice_failure: true

services:
    logger:
        class: Symfony\Component\HttpKernel\Log\Logger
        arguments:
            $minLevel: null
            $output: '%kernel.logs_dir%/%kernel.environment%.log'
            $formatter: null

    redlabteam_helpers.array:
        class: RedlabTeam\HelpersBundle\Service\ArrayService
        arguments:
            $logger: '@logger'
            $debug: '%redlabteam_helpers_debug%'
            $noticeFailure: '%redlabteam_helpers_notice_failure%'
    RedlabTeam\HelpersBundle\Service\ArrayService: '@redlabteam_helpers.array'

    redlabteam_helpers.date:
        class: RedlabTeam\HelpersBundle\Service\DateService
        arguments:
            $logger: '@logger'
            $debug: '%redlabteam_helpers_debug%'
            $noticeFailure: '%redlabteam_helpers_notice_failure%'
    RedlabTeam\HelpersBundle\Service\DateService: '@redlabteam_helpers.date'

    redlabteam_helpers.json:
        class: RedlabTeam\HelpersBundle\Service\JsonService
        arguments:
            $logger: '@logger'
            $debug: '%redlabteam_helpers_debug%'
            $noticeFailure: '%redlabteam_helpers_notice_failure%'
    RedlabTeam\HelpersBundle\Service\JsonService: '@redlabteam_helpers.json'

    redlabteam_helpers.string:
        class: RedlabTeam\HelpersBundle\Service\StringService
        arguments:
            $logger: '@logger'
            $debug: '%redlabteam_helpers_debug%'
            $noticeFailure: '%redlabteam_helpers_notice_failure%'
    RedlabTeam\HelpersBundle\Service\StringService: '@redlabteam_helpers.string'