parameters:

services:
    redlabteam_helpers.arr:
        class: RedlabTeam\Helper\Arr
    RedlabTeam\Helper\Arr: '@redlabteam_helpers.arr'

    redlabteam_helpers.date:
        class: RedlabTeam\Helper\Date
    RedlabTeam\Helper\Date: '@redlabteam_helpers.date'

    redlabteam_helpers.json:
        class: RedlabTeam\Helper\Json
    RedlabTeam\Helper\Json: '@redlabteam_helpers.json'